/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-container': '#e5eeff',
        'surface-container-low': '#eff4ff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#545f73',
        primary: '#000000',
        secondary: '#0051d5',
        tertiary: '#000000',
        'primary-fixed': '#d8e3fb',
        'primary-fixed-dim': '#bcc7de',
        'primary-container': '#111c2d',
        'secondary-container': '#316bf3',
        'secondary-fixed': '#dbe1ff',
        'secondary-fixed-dim': '#b4c5ff',
        'tertiary-container': '#40000c',
        'tertiary-fixed': '#ffdada',
        'tertiary-fixed-dim': '#ffb3b6',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#45464d',
        'on-background': '#0b1c30',
        'on-primary': '#ffffff',
        'on-primary-container': '#79849a',
        'on-primary-fixed': '#111c2d',
        'on-primary-fixed-variant': '#3c475a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#fefcff',
        'on-secondary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#003ea8',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f83256',
        'on-tertiary-fixed': '#40000c',
        'on-tertiary-fixed-variant': '#920028',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        navy: {
          50: '#e8edf5',
          100: '#c5d0e6',
          200: '#9db0d4',
          300: '#7490c2',
          400: '#5577b5',
          500: '#3a5ea8',
          600: '#2d4f97',
          700: '#1e3c82',
          800: '#142d6e',
          900: '#0f1f3d',
          950: '#091528',
        },
        brand: {
          green: '#16a34a',
          amber: '#d97706',
          red: '#dc2626',
        },
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        headline: ['Manrope', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
      fontSize: {
        '2xs': ['11px', { lineHeight: '14px' }],
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgba(0,0,0,0.05)',
        'card': '0 1px 3px 0 rgba(0,0,0,0.07), 0 1px 2px -1px rgba(0,0,0,0.07)',
        'card-hover': '0 4px 12px 0 rgba(0,0,0,0.1), 0 2px 4px -1px rgba(0,0,0,0.06)',
        'drawer': '-4px 0 24px 0 rgba(0,0,0,0.15)',
        'workspace': '0 18px 48px -28px rgba(15, 31, 61, 0.2)',
        'lg': '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)',
        'toast': '0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.1)',
      },
      keyframes: {
        'slide-in': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        'slide-in-bottom': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-out': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'slide-out-bottom': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
      },
      animation: {
        'slide-in': 'slide-in 0.25s ease-out',
        'slide-in-bottom': 'slide-in-bottom 0.25s ease-out',
        'fade-in': 'fade-in 0.2s ease-out',
        'slide-out': 'slide-out 0.2s ease-in',
        'slide-out-bottom': 'slide-out-bottom 0.2s ease-in',
        'shimmer': 'shimmer 2s infinite linear',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
      },
      borderRadius: {
        'xl': '12px',
        '2xl': '16px',
      },
    },
  },
  plugins: [],
}
